apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-transactions
spec:
  template:
    spec:
      containers:
      - name: kafka-init
        image: confluentinc/cp-kafka:7.5.0
        command: ["bash", "-c"]
        args:
          - |
            kafka-topics --create --if-not-exists \
              --topic transactions \
              --bootstrap-server kafka-service:9092 \
              --partitions 1 --replication-factor 1
      restartPolicy: OnFailure