apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data
        - name: archive-volume
          mountPath: /mnt/archive
      restartPolicy: Always
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: archive-volume
        persistentVolumeClaim:
          claimName: archive-pvc