apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-archive-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: /share1/archive   # or just /share1 if you want both PVCs to share
    server: 10.59.141.226   # same Filestore IP
  storageClassName: filestore-rwx
  persistentVolumeReclaimPolicy: Retain
